name: Build and Push

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      context-path:
        required: true
        type: string
      dockerfile-path:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.image-name }}

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set PR as Docker tag
        if: github.event_name == 'pull_request'
        run: echo "DOCKER_TAG=${{ steps.meta.outputs.version }}" >> $GITHUB_ENV

      - name: Set Docker tag to 'latest'
        if: github.ref == 'refs/heads/main'
        run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v3
        env:
          DOCKER_TAG: ${{ env.DOCKER_TAG }}
        with:
          context: ${{ inputs.context-path }}
          file: ${{ inputs.dockerfile-path }}
          push: true
          tags: ${{ inputs.image-name }}:${{ env.DOCKER_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
