name: gha-busy-box

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: 13angs/gha-busy-box

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract branch name from ref
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set Docker tag
        if: github.event_name == 'pull_request'
        run: echo "DOCKER_TAG=${{ env.BRANCH_NAME }}" >> $GITHUB_ENV

      - name: Set Docker tag to 'latest'
        if: github.ref == 'refs/heads/main'
        run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v3
        env:
          DOCKER_TAG: ${{ env.DOCKER_TAG }}
        with:
          context: ./samples/gha-busy-box
          file: ./samples/gha-busy-box/Dockerfile
          push: true
          tags: 13angs/gha-busy-box:${{ env.DOCKER_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
