name: CI

on:
  pull_request:
    paths:
      - 'samples/busy-box/**'
      - 'samples/webhook/**'
    branches:
      - main
  push:
    paths:
      - 'samples/busy-box/**'
      - 'samples/webhook/**'
    branches:
      - main

jobs:
  busy-box:
    if: contains(github.event.commits.*.modified, 'samples/busy-box/')
    uses: ./.github/workflows/build.yml
    with:
      image-name: 13angs/gha-busy-box
      context-path: ./samples/busy-box
      dockerfile-path: ./samples/busy-box/Dockerfile
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  webhook:
    if: contains(github.event.commits.*.modified, 'samples/webhook/')
    uses: ./.github/workflows/build.yml
    with:
      image-name: 13angs/gha-webhook
      context-path: ./samples/webhook
      dockerfile-path: ./samples/webhook/Dockerfile
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
